<a href="https://colab.research.google.com/github/Vipulkumarkaushik/AlgoVisualizer/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
c = np.array([[1,1,1],[2,2,2],[3,3,3]])
print(c)

[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [ ]:
#GET DIMENSIONS
a.ndim

1

In [ ]:
c.ndim

2

In [ ]:
b.ndim

2